name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build and test
    runs-on: windows-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v7

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Run cargo test
        run: cargo test --verbose

  lints:
    name: Lints
    runs-on: windows-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v7

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

      - name: Run cargo clippy
        run: cargo clippy --all-targets -- -D warnings
